const HBCUs = [
  "Alabama A&M University",
  "Alabama State University",
  "Albany State University",
  "Alcorn State University",
  "Allen University",
  "American Baptist College",
  "University of Arkansas at Pine Bluff",
  "Arkansas Baptist College",
  "Barber-Scotia College",
  "Benedict College",
  "Bennett College",
  "Bethune-Cookman University",
  "Bishop State Community College",
  "Bluefield State College",
  "Bowie State University",
  "Carver College",
  "Central State University",
  "Cheyney University of Pennsylvania",
  "Claflin University",
  "Clark Atlanta University",
  "Clinton College",
  "Coahoma Community College",
  "Coppin State University",
  "Delaware State University",
  "Denmark Technical College",
  "Dillard University",
  "University of the District of Columbia",
  "Edward Waters University",
  "Elizabeth City State University",
  "Fayetteville State University",
  "Fisk University",
  "Florida A&M University",
  "Florida Memorial University",
  "Fort Valley State University",
  "Grambling State University",
  "Hampton University",
  "Harris-Stowe State University",
  "Howard University",
  "Huston-Tillotson University",
  "Jackson State University",
  "Jarvis Christian College",
  "Johnson C. Smith University",
  "Kentucky State University",
  "Lane College",
  "Langston University",
  "Lawson State Community College",
  "LeMoyne-Owen College",
  "Lincoln University (MO)",
  "Lincoln University (PA)",
  "Livingstone College",
  "University of Maryland Eastern Shore",
  "Meharry Medical College",
  "Miles College",
  "Mississippi Valley State University",
  "Morehouse College",
  "Morgan State University",
  "Morris Brown College",
  "Norfolk State University",
  "North Carolina A&T State University",
  "North Carolina Central University",
  "Oakwood University",
  "Paine College",
  "Paul Quinn College",
  "Philander Smith College",
  "Prairie View A&M University",
  "Rust College",
  "Savannah State University",
  "Selma University",
  "Shaw University",
  "Shorter College",
  "Simmons College of Kentucky",
  "South Carolina State University",
  "Southern University at New Orleans",
  "Southern University at Shreveport",
  "Southern University and A&M College",
  "Southwestern Christian College",
  "Spelman College",
  "St. Augustine's University",
  "St. Philip's College",
  "Stillman College",
  "Talladega College",
  "Tennessee State University",
  "Texas College",
  "Texas Southern University",
  "Tougaloo College",
  "Tuskegee University",
  "University of the Virgin Islands",
  "Virginia State University",
  "Virginia Union University",
  "Virginia University of Lynchburg",
  "Voorhees University",
  "West Virginia State University",
  "Wilberforce University",
  "Wiley College",
  "Winston-Salem State University",
  "Xavier University of Louisiana",
  "Other",
];

export default HBCUs;
